"""athar -- the fine arrives weeks later, addressed to a car."""

import argparse
import os
import sys
from datetime import date, datetime

from . import agents, assignments, fines, report, rules
from .config import Config


def build_parser():
    p = argparse.ArgumentParser(
        prog="athar",
        description="Fleet fine attribution: the custody join, the dispute "
                    "clock and the evidence check are computed, never "
                    "generated by a model. A fine the data cannot settle is "
                    "reported as contested, and nobody is named.",
    )
    p.add_argument("fines", help="fines CSV")
    p.add_argument("--assignments", default=None,
                   help="custody record CSV (default: alongside the fines "
                        "file, named assignments.csv)")
    p.add_argument("-o", "--out", default="attributions.csv",
                   help="attribution CSV")
    p.add_argument("--config", default=None,
                   help="JSON overriding windows, buffers and thresholds")
    p.add_argument("--today", default=None,
                   help="YYYY-MM-DD, for reproducible runs")
    p.add_argument("--show-all", action="store_true",
                   help="list every fine, not only actionable ones")
    p.add_argument("--no-agents", action="store_true",
                   help="computed ledger only; no model calls")
    p.add_argument("--fail-on", default="none",
                   choices=("none", "contested", "held"),
                   help="exit non-zero at this state (for a scheduled run)")
    p.add_argument("--no-colour", action="store_true")
    return p


def build_task(ledger, assignment_rows):
    """One task per run, or none.

    A run with nothing in an actionable band has nothing to advise on and is
    not sent to a model to produce filler.

    `fleet_driver_ids` carries every driver identifier that exists anywhere
    in the custody file -- not only the ones attributed. That is what lets
    the gate catch a draft naming somebody the engine declined to name: the
    name is real, it is simply not established for this fine.
    """
    if not ledger.actionable():
        return None
    facts = ledger.facts()
    facts["fleet_driver_ids"] = sorted(
        {a.driver_id for a in assignment_rows if a.driver_id})
    return {
        "batch_id": ledger.today.isoformat(),
        "label": f"{len(ledger.actionable())} actionable fine(s) as of "
                 f"{ledger.today.isoformat()}",
        "facts": facts,
        "allowed": agents.expand_evidence(facts),
    }


def main(argv=None):
    args = build_parser().parse_args(argv)

    today = date.today()
    if args.today:
        try:
            today = datetime.strptime(args.today, "%Y-%m-%d").date()
        except ValueError:
            print(f"athar: --today must be YYYY-MM-DD, got {args.today}",
                  file=sys.stderr)
            return 2

    try:
        cfg = Config.load(args.config)
    except (OSError, ValueError) as exc:
        print(f"athar: config: {exc}", file=sys.stderr)
        return 2

    if not os.path.isfile(args.fines):
        print(f"athar: {args.fines} not found", file=sys.stderr)
        return 2

    asg_path = args.assignments or os.path.join(
        os.path.dirname(os.path.abspath(args.fines)), "assignments.csv")
    if not os.path.isfile(asg_path):
        print(f"athar: {asg_path} not found -- pass --assignments",
              file=sys.stderr)
        return 2

    try:
        fine_rows = fines.load(args.fines)
        assignment_rows = assignments.load(asg_path)
    except (OSError, ValueError) as exc:
        print(f"athar: {exc}", file=sys.stderr)
        return 2

    ledger = rules.assess(fine_rows, assignment_rows, cfg, today)

    task = build_task(ledger, assignment_rows)
    agentic = not args.no_agents and task is not None
    if agentic:
        try:
            [task] = agents.run([task])
        except agents.AgentUnavailable as exc:
            print(f"athar: {exc}", file=sys.stderr)
            print("athar: falling back to the computed ledger.", file=sys.stderr)
            agentic = False

    if agentic:
        agents.gate(task, task["allowed"])
    else:
        task = None

    print(report.terminal(ledger, cfg, agentic, task,
                          use_colour=not args.no_colour,
                          show_all=args.show_all))

    report.write_csv(args.out, ledger)
    print(f"  attributions -> {args.out}")
    print("")

    if args.fail_on == "contested" and ledger.by_state("CONTESTED"):
        return 1
    if args.fail_on == "held" and task and task.get("status") == "held":
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
