"""masar -- the approval sequence nobody has written down."""

import argparse
import os
import sys
from datetime import date, datetime

from . import agents, projects, report, rules
from .config import Config


def build_parser():
    p = argparse.ArgumentParser(
        prog="masar",
        description="Construction approval sequencing: prerequisite checks, "
                    "critical path and every forecast date are computed, "
                    "never generated by a model. A submission already filed "
                    "out of sequence is flagged as WILL_BOUNCE before the "
                    "authority gets to say so.",
    )
    p.add_argument("projects", help="project approval-state CSV")
    p.add_argument("-o", "--out", default="schedule.csv", help="schedule CSV")
    p.add_argument("--config", default=None,
                   help="JSON overriding the approval graph and cycle times")
    p.add_argument("--today", default=None, help="YYYY-MM-DD, for reproducible runs")
    p.add_argument("--project", default=None, help="assess one project only")
    p.add_argument("--show-granted", action="store_true",
                   help="list already-granted approvals too")
    p.add_argument("--no-agents", action="store_true",
                   help="computed schedule only; no model calls")
    p.add_argument("--fail-on", default="none",
                   choices=("none", "will-bounce", "held"),
                   help="exit non-zero at this state (for a scheduled run)")
    p.add_argument("--no-colour", action="store_true")
    return p


def build_tasks(assessments):
    """One task per project with something to advise on.

    A project whose every approval is granted has nothing to sequence, and a
    project with no READY or BLOCKED approvals has nothing actionable — both
    are skipped rather than sent to a model to produce filler.
    """
    tasks = []
    for a in assessments:
        actionable = [r for r in a.readiness
                      if r.verdict in ("WILL_BOUNCE", "READY", "RISKY", "BLOCKED")]
        if not actionable:
            continue
        facts = a.facts()
        tasks.append({
            "project_id": a.project_id,
            "label": f"{a.project_id} {a.project_name} ({a.jurisdiction})",
            "facts": facts,
            "allowed": agents.expand_evidence(facts),
        })
    return tasks


def main(argv=None):
    args = build_parser().parse_args(argv)

    today = date.today()
    if args.today:
        try:
            today = datetime.strptime(args.today, "%Y-%m-%d").date()
        except ValueError:
            print(f"masar: --today must be YYYY-MM-DD, got {args.today}",
                  file=sys.stderr)
            return 2

    try:
        cfg = Config.load(args.config)
    except (OSError, ValueError) as exc:
        print(f"masar: config: {exc}", file=sys.stderr)
        return 2

    if not os.path.isfile(args.projects):
        print(f"masar: {args.projects} not found", file=sys.stderr)
        return 2

    try:
        loaded = projects.load(args.projects)
    except (OSError, ValueError) as exc:
        print(f"masar: {exc}", file=sys.stderr)
        return 2

    if args.project:
        loaded = [p for p in loaded if p.project_id == args.project]
        if not loaded:
            print(f"masar: project {args.project} not found", file=sys.stderr)
            return 2

    assessments = [rules.assess(p, cfg, today) for p in loaded]

    tasks = build_tasks(assessments)
    agentic = not args.no_agents and bool(tasks)
    if agentic:
        try:
            tasks = agents.run(tasks)
        except agents.AgentUnavailable as exc:
            print(f"masar: {exc}", file=sys.stderr)
            print("masar: falling back to the computed schedule.", file=sys.stderr)
            agentic = False

    if agentic:
        for t in tasks:
            agents.gate(t, t["allowed"])
        review = tasks
    else:
        review = []

    print(report.terminal(assessments, cfg, agentic, review,
                          use_colour=not args.no_colour,
                          show_granted=args.show_granted))

    report.write_csv(args.out, assessments, review)
    print(f"  schedule -> {args.out}")
    print("")

    if args.fail_on == "will-bounce" and any(a.will_bounce() for a in assessments):
        return 1
    if args.fail_on == "held" and any(t.get("status") == "held" for t in review):
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
